### ISSUE TITLE
Reduce token permissions in actions

### ISSUE THREAD

**Issue by friedelwolff** [SADiLaR/term_platform#142]
We are currently close to defaults with regards to security in github actions. From a quick look, we should be able to move to read-only permissions, and maybe limit it ever further.

Let's investigate what is easy to do, and get the necessary bugs filed. If it is easy and quick, let's sommer do it right away.

**Comment by Restioson** [comment]
Further reading:
- https://johnstawinski.com/2024/01/11/playing-with-fire-how-we-executed-a-critical-supply-chain-attack-on-pytorch/
- https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions
- https://github.com/woodruffw/zizmor
